version: '3.8'
services:
  backend:
    image: vladimirhristovski/ecommerce-backend
    build:
      context: ./Backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    image: vladimirhristovski/ecommerce-frontend
    build:
      context: ./Frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: