create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(100),
    continent varchar(100)
);

create table host
(
    id      bigint generated by default as identity primary key,
    name    varchar(100),
    surname varchar(100),
    country bigint references country
);

create table accommodation
(
    id        bigint generated by default as identity primary key,
    name      varchar(100),
    category  varchar(100),
    host      bigint references host,
    num_rooms integer,
    rented    boolean default false
);

create table lab_users
(
    username                   varchar(100) primary key,
    password                   varchar(100),
    name                       varchar(100),
    surname                    varchar(100),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    id_enabled                 boolean default true,
    role                       varchar(100)
);

create table temporary_reservations
(
    id            bigint generated by default as identity primary key,
    date_created  timestamp,
    user_username varchar(100) references lab_users,
    status        varchar(100)
);

create table temporary_reservations_accommodations
(
    temporary_reservations_id bigint references temporary_reservations on delete cascade,
    accommodation_id          bigint references accommodation on delete cascade,
    primary key (temporary_reservations_id, accommodation_id)
);

create index idx_tr_user_status on temporary_reservations (user_username, status);
create index idx_user_username_password on lab_users (username, password);
create index idx_user_username on lab_users (username);
create index idx_user_role on lab_users (role);